### ISSUE TITLE
Direct input to integer conversions cause crash on invalid input.

### ISSUE THREAD

**Issue by acureau** [DuhonTheGuy/RPG-Generator#9]
For example typing "word" on the main menu instead of a choice will error.

**Comment by DuhonTheGuy** [comment]
Without looking into it, this seems like something a quick try except statement/some if else trickery could solve, pretty beginner-friendly, too.

**Comment by acureau** [comment]
> Without looking into it, this seems like something a quick try except statement/some if else trickery could solve, pretty beginner-friendly, too.

Yup, my thoughts as well. I was planning on going the try / except route

**Comment by daspartho** [comment]
can you assign it to me

**Comment by daspartho** [comment]
I'll work on this

**Comment by ghost** [comment]
#12 Should be fixed if this gets merged.

**Comment by DuhonTheGuy** [comment]
Got merged, so I'll close this as soon as I test it (in a few days).
